# Multi-Agent Requirements Gathering System Configuration

# Workflow Configuration
workflow:
  max_iterations: 3                    # Maximum refinement iterations
  ambiguity_threshold: 0.3             # Threshold for triggering stakeholder simulation
  validation_threshold: 0.7            # Threshold for passing validation
  enable_human_escalation: false       # Human escalation disabled - not implemented
  parallel_processing: false           # Enable parallel agent processing (experimental)

# Agent Configuration
agent:
  model_name: "gpt-4o-mini"            # OpenAI model to use
  temperature: 0.1                     # Model temperature (0.0-2.0)
  max_tokens: null                     # Maximum tokens per response (null for model default)
  timeout: 60                          # Request timeout in seconds

# OpenAI Configuration (can be overridden by environment variables)
openai:
  api_key: null                        # Set via OPENAI_API_KEY environment variable
  organization: null                   # Set via OPENAI_ORGANIZATION environment variable
  base_url: null                       # Set via OPENAI_BASE_URL environment variable

# Logging Configuration
logging:
  level: "INFO"                        # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null                           # Log file path (null for console only)
  max_bytes: 10485760                  # Max log file size (10MB)
  backup_count: 5                      # Number of backup log files

# Output Configuration
output:
  directory: "output"                  # Output directory for results
  format: "json"                       # Output format (json, yaml)
  include_metadata: true               # Include processing metadata
  compress: false                      # Compress output files

# Performance Configuration
performance:
  cache_enabled: true                  # Enable response caching
  cache_ttl: 3600                      # Cache time-to-live in seconds
  max_concurrent_requests: 5           # Maximum concurrent API requests
  request_timeout: 30                  # Individual request timeout